// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`authenticate when called back by the third party raises an AuthenticationFailed error if there is an error query parameter 1`] = `
[AuthenticationFailed: Authentication failed:
{
  "error": "test_code",
  "error_description": "oops"
}]
`;

exports[`authenticate when connecting redirects to the authorization url with correct params 1`] = `
[MockFunction] {
  "calls": Array [
    Array [
      Object {
        "authorizationParams": Object {
          "someAuthParam": "test-ap",
        },
        "authorizationURL": "https://example.com/auth",
        "callbackURL": "https://example.com/v2/auth/callback",
        "clientId": "test-client-id",
        "scope": Array [
          "test-scope1",
          "test-scope2",
        ],
        "state": "test-state",
      },
    ],
  ],
  "results": Array [
    Object {
      "isThrow": false,
      "value": "https://example.com/auth?with_params=true",
    },
  ],
}
`;
